services:
  postgres:
    image: freeradius_3.2.7
    container_name: freeradius-alpine
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    volumes:
      - ./configs/freeradius:/etc/freeradius